<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Law_Connect</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="IAM\Domain\Repositories\**" />
    <Compile Remove="IAM\Domain\Services\**" />
    <Compile Remove="IAM\Interface\**" />
    <Content Remove="IAM\Domain\Repositories\**" />
    <Content Remove="IAM\Domain\Services\**" />
    <Content Remove="IAM\Interface\**" />
    <EmbeddedResource Remove="IAM\Domain\Repositories\**" />
    <EmbeddedResource Remove="IAM\Domain\Services\**" />
    <EmbeddedResource Remove="IAM\Interface\**" />
    <None Remove="IAM\Domain\Repositories\**" />
    <None Remove="IAM\Domain\Services\**" />
    <None Remove="IAM\Interface\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.CreatedUpdatedDate" Version="8.0.0" />
    <PackageReference Include="Humanizer" Version="2.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational.Design" Version="1.1.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="8.0.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>
<ItemGroup>
  <Folder Include="IAM\Domain\Aggregates\" />
  <Folder Include="IAM\Domain\ValueObjects\" />
</ItemGroup>
</Project>
